62 Use OntoViewer Toolkit for generating datadictionary
edmcouncil/ontology-publisher pull request #63
Opened 2021-11-09 07:21 UTC by trojczak

Signed-off-by: Rafał Trójczak <rafal@trojczak.pl>

2021-11-23 13:43 UTC, mereolog requested changes
I got this error when I ran all products (against the latest version of FIBO):

```
2021-11-23 13:26:34.894 DEBUG 32278 --- [           main] o.e.s.o.t.OntoViewerToolkitCommandLine   : Loaded ontology contains 161336 axioms.
2021-11-23 13:33:00.556  INFO 32278 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-11-23 13:33:00.689 ERROR 32278 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794) ~[spring-boot-2.5.2.jar!/:2.5.2]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) ~[spring-boot-2.5.2.jar!/:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.2.jar!/:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.2.jar!/:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.2.jar!/:2.5.2]
	at org.edmcouncil.spec.ontoviewer.toolkit.OntoViewerToolkitApplication.main(OntoViewerToolkitApplication.java:10) ~[classes!/:0.4.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[onto-viewer-toolkit.jar:0.4.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[onto-viewer-toolkit.jar:0.4.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[onto-viewer-toolkit.jar:0.4.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[onto-viewer-toolkit.jar:0.4.0]
Caused by: java.lang.NullPointerException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at org.edmcouncil.spec.ontoviewer.toolkit.handlers.OntologyTableDataExtractor.getEntities(OntologyTableDataExtractor.java:99) ~[classes!/:0.4.0]
	at org.edmcouncil.spec.ontoviewer.toolkit.handlers.OntologyTableDataExtractor.extractEntityData(OntologyTableDataExtractor.java:67) ~[classes!/:0.4.0]
	at org.edmcouncil.spec.ontoviewer.toolkit.OntoViewerToolkitCommandLine.run(OntoViewerToolkitCommandLine.java:67) ~[classes!/:0.4.0]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) ~[spring-boot-2.5.2.jar!/:2.5.2]
	... 13 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.edmcouncil.spec.ontoviewer.core.ontology.data.OwlDataHandler.handleParticularIndividual(OwlDataHandler.java:285) ~[onto-viewer-core-0.4.0.jar!/:0.4.0]
	at org.edmcouncil.spec.ontoviewer.core.ontology.DetailsManager.getDetailsByIri(DetailsManager.java:76) ~[onto-viewer-core-0.4.0.jar!/:0.4.0]
	at org.edmcouncil.spec.ontoviewer.toolkit.handlers.OntologyTableDataExtractor.lambda$getEntities$1(OntologyTableDataExtractor.java:91) ~[classes!/:0.4.0]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926) ~[na:na]
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]

======================================= Writing from csv files to xlsx files
Traceback (most recent call last):
  File "/publisher/lib/csv-to-xlsx.py", line 41, in <module>
    with open(inputfile, 'rt', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/output/fibo/datadictionary/master/latest/datadictionary-prod.csv'
```

2021-11-29 13:54 UTC, mereolog commented
I cannot reproduce https://github.com/edmcouncil/ontology-publisher/pull/63#pullrequestreview-813675237 anymore.

2021-11-30 12:38 UTC, przemekgradzki approved these changes

2021-11-30 12:39 UTC, merged

2021-11-30 12:40 UTC, przemekgradzki commented
Resolves #62