Add messages with error and warning counters in the hygiene test logs
edmcouncil/ontology-publisher pull request #96
Opened 2022-05-06 06:05 UTC by przemekgradzki

Closes #95

2022-05-11 09:44 UTC, mereolog requested changes
@przemekgradzki when I ran it locally (in docker MacOs 12.0.1) against https://github.com/edmcouncil/idmp/commit/cfdb831cb71f905f1a0193323c4184e2eec12ec7:
`env ONTPUB_FAMILY=idmp DEV_SPEC=AboutIDMPDev.rdf PROD_SPEC=AboutIDMPProd.rdf HYGIENE_TEST_PARAMETER_VALUE="idmp|omg" ./docker-run.sh --shell --rebuild`

and then `./publish.sh hygiene` I got these errors:

```
error: failed to write new configuration file /var/tmp/.gitconfig.lock
error: failed to write new configuration file /var/tmp/.gitconfig.lock
...
ONTOVIEWER_TOOLKIT_JAVA = java -Dlogging.level.org.edmcouncil.spec.ontoviewer=INFO -Dlogging.level.org.edmcouncil.spec.ontoviewer.toolkit=DEBUG -Dlogging.level.org.springframework=INFO -jar /usr/share/java/onto-viewer/onto-viewer-toolkit.jar
Git status:
On branch idmp-114
Your branch is up to date with 'origin/idmp-114'.
...
 - tag_root                  : [<tag_root>] (is empty)
 - tag_root_url              : [https://spec.edmcouncil.org/idmp/ontology/idmp-114/latest]
mkdir: cannot create directory ‘/var/tmp/hygiene/’: No space left on device
Traceback (most recent call last):
  File "/publisher/lib/hygiene_tests_parametizer.py", line 28, in <module>
    parameterise_hygiene_test(
  File "/publisher/lib/hygiene_tests_parametizer.py", line 15, in parameterise_hygiene_test
    output_file = open(output_file_path, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/hygiene/testHygiene_circular_definitions.sparql'
Merging all dev ontologies into one RDF file
Traceback (most recent call last):
  File "/publisher/lib/ontology_collector.py", line 73, in <module>
    collect_ontologies(
  File "/publisher/lib/ontology_collector.py", line 55, in collect_ontologies
    output_graph.serialize(output_graph_path)
  File "/usr/lib/python3.9/site-packages/rdflib/graph.py", line 1134, in serialize
    fd, name = tempfile.mkstemp()
  File "/usr/lib/python3.9/tempfile.py", line 325, in mkstemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
  File "/usr/lib/python3.9/tempfile.py", line 118, in _sanitize_params
    dir = gettempdir()
  File "/usr/lib/python3.9/tempfile.py", line 287, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python3.9/tempfile.py", line 219, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/var/tmp', '/tmp', '/var/tmp', '/usr/tmp', '/publisher']
Merging dev ontologies encountered problem(s), so hygiene test results may be incomplete.
Merging all prod ontologies into one RDF file
Traceback (most recent call last):
  File "/publisher/lib/ontology_collector.py", line 73, in <module>
    collect_ontologies(
  File "/publisher/lib/ontology_collector.py", line 55, in collect_ontologies
    output_graph.serialize(output_graph_path)
  File "/usr/lib/python3.9/site-packages/rdflib/graph.py", line 1134, in serialize
    fd, name = tempfile.mkstemp()
  File "/usr/lib/python3.9/tempfile.py", line 325, in mkstemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
  File "/usr/lib/python3.9/tempfile.py", line 118, in _sanitize_params
    dir = gettempdir()
  File "/usr/lib/python3.9/tempfile.py", line 287, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python3.9/tempfile.py", line 219, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/var/tmp', '/tmp', '/var/tmp', '/usr/tmp', '/publisher']
Merging prod ontologies encountered problem(s), so hygiene test results may be incomplete.
======================================= Will run the following tests:
find: ‘/var/tmp/hygiene/’: No such file or directory
======================================= Errors in DEV:
find: ‘/var/tmp/hygiene/’: No such file or directory
======================================= Errors in PROD:
find: ‘/var/tmp/hygiene/’: No such file or directory
======================================= Passed all the hygiene tests
Finished hygiene tests
End of "./publish hygiene", rc=0

```

2022-05-12 07:31 UTC, przemekgradzki commented
@mereolog see the message:
> mkdir: cannot create directory ‘/var/tmp/hygiene/’: No space left on device

this is a problem on your computer.

2022-05-12 08:25 UTC, mereolog requested changes
1. Be consistent with colors, so all counts should be displayed in green.
3. 'DEV/PROD warnings count' > 'DEV/PROD all warnings count'
4. We do not need 'all warnings count : ...', so please remove it.

2022-05-12 13:18 UTC, mereolog approved these changes

2022-05-12 13:18 UTC, merged